add mint_component

diff --git a/mint_component/src/run b/mint_component/src/run
--- a/mint_component/src/run
+++ b/mint_component/src/run
@@ -1,6 +1,31 @@
 #!/bin/bash
+set -xe
 
-pitremove -z $1 -fel demfel.tif
+checkExitCode() {
+if [ $? -ne 0 ]; then
+    echo "Error"
+    exit 1;
+fi
+}
+
+BASEDIR=`dirname $0`
+
+. $BASEDIR/io.sh 1 1 2 "$@"
+
+set -x
+
+replace_file() {
+    arg_key=$1
+    file=$2
+    arg_value=$3
+
+    line_time=$(grep -n "^${arg_key}" ${file} | cut -d : -f 1)
+    sed "${line_time}d" -i ${file}
+    sed -e "${line_time}i${arg_key} | ${arg_value} | ${4} | ${5}" -i ${file}
+}
+
+CURDIR=`pwd`
+pitremove -z $INPUTS1 -fel demfel.tif
 dinfflowdir -fel demfel.tif -ang demang.tif -slp demslp.tif
 d8flowdir -fel demfel.tif -p demp.tif -sd8 demsd8.tif
 aread8 -p demp.tif -ad8 demad8.tif -nc
@@ -11,7 +36,7 @@ slopearea -slp demslp.tif -sca demsca.tif -sa demsa.tif
 d8flowpathextremeup -p demp.tif -sa demsa.tif -ssa demssa.tif -nc
 python3 hand-thresh.py --resolution demfel.tif --output demthresh.txt
 #threshold -ssa demssa.tif -src demsrc.tif -thresh $(cat demthresh.txt)
-threshold -ssa demssa.tif -src demsrc.tif -thresh 500
+threshold -ssa demssa.tif -src demsrc.tif -thresh $PARAMETERS1
 
 streamnet -fel demfel.tif -p demp.tif -ad8 demad8.tif -src demsrc.tif -ord demord.tif -tree demtree.dat -coord demcoord.dat -net demnet.shp -w demw.tif -sw
 
@@ -27,3 +52,6 @@ dropanalysis -ad8 demad8.tif -p demp.tif -fel demfel.tif -ssa demssa.tif -o outl
 threshold -ssa demssa.tif -src demsrc.tif -thresh $(tail -n 1 demdrp.txt | awk '{print $NF}')
 
 dinfdistdown -ang demang.tif -fel demfel.tif -src demsrc.tif -wg demwg.tif -dd $2 -m ave v -nc
+
+mv output.tif $OUTPUTS1
+mv output.png $OUTPUTS2
